service: execucioPeriodicaLambdaTutorial


provider:
  name: aws
  profile: SchramsServerless
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 128
  executionTime: 1



functions:
  FuncioCada50min:
    handler: handler.FuncioCada50min
    events:
      - schedule: rate(50 minutes)

  funcioCadaDia12PM:
    handler: handler.funcioCadaDia12PM
    events:
      - schedule: cron(0 12 * * ? *)